### ISSUE TITLE
Bug report: Parcel + PostCSS build error message

### ISSUE THREAD

**Issue by livmari** [livmari/queenslab-codetest#1]
# This issue is a note to self

## Build error message
```
🚨 Build Error
/Users/livalterskjaer/dev/queenslab-codetest/src/index.css:undefined:undefined: PostCSS plugin tailwindcss requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users

Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/Users/livalterskjaer/.config/yarn/global/node_modules/postcss/lib/processor.js:153:15)
    at new Processor (/Users/livalterskjaer/.config/yarn/global/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/Users/livalterskjaer/.config/yarn/global/node_modules/postcss/lib/postcss.js:55:10)
    at module.exports (/Users/livalterskjaer/.config/yarn/global/node_modules/parcel-bundler/src/transforms/postcss.js:17:19)
    at async CSSAsset.transform (/Users/livalterskjaer/.config/yarn/global/node_modules/parcel-bundler/src/assets/CSSAsset.js:133:5)
    at async CSSAsset.process (/Users/livalterskjaer/.config/yarn/global/node_modules/parcel-bundler/src/Asset.js:216:7)
    at async Pipeline.processAsset (/Users/livalterskjaer/.config/yarn/global/node_modules/parcel-bundler/src/Pipeline.js:46:7)
    at async Pipeline.process (/Users/livalterskjaer/.config/yarn/global/node_modules/parcel-bundler/src/Pipeline.js:24:23)
    at async Object.run (/Users/livalterskjaer/.config/yarn/global/node_modules/parcel-bundler/src/worker.js:15:12)
    at async Child.handleRequest (/Users/livalterskjaer/.config/yarn/global/node_modules/@parcel/workers/src/child.js:60:26)
```

## Current PostCSS version
`"postcss": "^8.2.3",`

**Comment by livmari** [comment]
# Update
Probably solved by installing `postcss-loader`, but need to confirm after the new error message that came after this one is fixed.

## Build error message
```
🚨 Build Error
The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received null

    at new NodeError (node:internal/errors:278:15)
    at Hash.update (node:internal/crypto/hash:105:11)
    at Bundle.getHash (/Users/livalterskjaer/.config/yarn/global/node_modules/parcel-bundler/src/Bundle.js:301:12)
    at Bundle.package (/Users/livalterskjaer/.config/yarn/global/node_modules/parcel-bundler/src/Bundle.js:186:23)
    at Bundle.package (/Users/livalterskjaer/.config/yarn/global/node_modules/parcel-bundler/src/Bundle.js:198:30)
    at Bundle.package (/Users/livalterskjaer/.config/yarn/global/node_modules/parcel-bundler/src/Bundle.js:198:30)
    at Bundler.bundle (/Users/livalterskjaer/.config/yarn/global/node_modules/parcel-bundler/src/Bundler.js:325:49)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Timeout._onTimeout (/Users/livalterskjaer/.config/yarn/global/node_modules/parcel-bundler/src/Bundler.js:817:7)
```

**Comment by livmari** [comment]
It was literally mentioned in the tailwindcss setup page. Issue has been fixed.
